name: Update Website

on:
  schedule:
    # 每天 9:30 AM (UTC+8) 执行 day_trading.py
    - cron: '30 0 * * *'  # 每天 UTC 1:30 执行（即北京时间 9:30）
  push:
    branches:
      - main  # 只要 main 分支有更新，自动触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装 requirements.txt 中列出的所有依赖包

      - name: Run day_trading.py script
        run: python trading.py  # 只运行 trading.py
